= Software Documentation for the {projectName}
:doctype: book
:toc: left
:toclevels: 3
:sectnumlevels: 5
:leveloffset: 1
:icons: font
:copyright: Open Logistics Foundation License 1.3
:projectName: NFT Folder

[[section-preface]]
= Preface

== Motivation

This is a subproject of the https://git.openlogisticsfoundation.org/wg-electronictransportdocuments/ecmr/ecmr[eCMR service].

== Documentation Approach

The documentation of this project is in English and is based on the link:https://docs.arc42.org/home/[arc42 template]

The link:https://agilemanifesto.org/[Agile Manifesto] says: “Working software over comprehensive documentation”.
It does *not* say “no documentation”.
Even in lean, agile and iterative development approaches, an appropriate amount of documentation will help numerous stakeholders doing a better job.
arc42 is completely process-agnostic, and especially well-suited for lean and agile development approaches.
It is supposed to be used “on demand” - you provide only the type or amount of information required for your specific documentation purpose.
Documentation shall be part of your Definition-of-Done.
Therefore, arc42 is _automatically_ included in Scrum processes.

https://docs.gitlab.com/ee/user/asciidoc.html[GitLab Asciidoc] gives an overview about using asciidoc in a GitLab project.

== Main Authors

[cols="1e,2e",options="header"]
|===
|Name
|E-Mail

|Dominik Buß
|dominik.buß@iml.fraunhofer.de

|Stephan Frerichs
|stephan.frerichs@iml.fraunhofer.de

|Lukas Grieger
|lukas.grieger@iml.fraunhofer.de

|Tobias Jornitz
|tobias.jornitz@iml.fraunhofer.de

|Alexander Needham
|alexander.needham@iml.fraunhofer.de

|Michael Pichura
|michael.pichura@iml.fraunhofer.de

|Dominik Sparer
|dominik.sparer@iml.fraunhofer.de
|===

:sectnums:

<<<
include::05_building_block_view.adoc[]

<<<
include::06_runtime_view.adoc[]

<<<
include::07_deployment_view.adoc[]

<<<
include::08_concepts.adoc[]

<<<
include::12_tutorial.adoc[]
